name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace '3.x' with the specific version you need

      - name: Install dependencies
        run: make install

      - name: Run the application
        run: |
          make run &
          sleep 10  # Adjust the time as needed to ensure the server starts up
